# -*- coding: utf-8 -*-
"""Book Scrapper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17SpK5D0xuTAaICRnmMviTcCNNrirwZ3Z
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://books.toscrape.com/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

books = soup.select("article.product_pod")

data = []

for book in books:
    title = book.h3.a['title']
    price = book.select_one('p.price_color').text.replace('£', '').replace('Â', '')
    availability = book.select_one('p.instock.availability').text.strip()
    star_class = book.p['class']
    rating = [c for c in star_class if c != 'star-rating'][0]

    data.append({
        'Title': title,
        'Price': float(price),
        'Availability': availability,
        'Rating': rating
    })

df = pd.DataFrame(data)
df.to_csv('books_basic.csv', index=False)
df.head()

from google.colab import files
files.download('books_basic.csv')  # or 'books_multipage.csv'